'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:2.0.50727.4952
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings 자동 저장 기능"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property StreamFrm_Volume() As Integer
            Get
                Return CType(Me("StreamFrm_Volume"),Integer)
            End Get
            Set
                Me("StreamFrm_Volume") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property StreamFrm_AllChToolStripMenuItem() As Boolean
            Get
                Return CType(Me("StreamFrm_AllChToolStripMenuItem"),Boolean)
            End Get
            Set
                Me("StreamFrm_AllChToolStripMenuItem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StreamFrm_LeftChToolStripMenuItem() As Boolean
            Get
                Return CType(Me("StreamFrm_LeftChToolStripMenuItem"),Boolean)
            End Get
            Set
                Me("StreamFrm_LeftChToolStripMenuItem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StreamFrm_RightChToolStripMenuItem() As Boolean
            Get
                Return CType(Me("StreamFrm_RightChToolStripMenuItem"),Boolean)
            End Get
            Set
                Me("StreamFrm_RightChToolStripMenuItem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property StreamFrm_rateM() As Single
            Get
                Return CType(Me("StreamFrm_rateM"),Single)
            End Get
            Set
                Me("StreamFrm_rateM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StreamFrm_scaletempoToolStripMenuItem() As Boolean
            Get
                Return CType(Me("StreamFrm_scaletempoToolStripMenuItem"),Boolean)
            End Get
            Set
                Me("StreamFrm_scaletempoToolStripMenuItem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StreamFrm_extrastereoToolStripMenuItem() As Boolean
            Get
                Return CType(Me("StreamFrm_extrastereoToolStripMenuItem"),Boolean)
            End Get
            Set
                Me("StreamFrm_extrastereoToolStripMenuItem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StreamFrm_karaokeToolStripMenuItem() As Boolean
            Get
                Return CType(Me("StreamFrm_karaokeToolStripMenuItem"),Boolean)
            End Get
            Set
                Me("StreamFrm_karaokeToolStripMenuItem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StreamFrm_VisualizeMotionVectorsToolStripMenuItem() As Boolean
            Get
                Return CType(Me("StreamFrm_VisualizeMotionVectorsToolStripMenuItem"),Boolean)
            End Get
            Set
                Me("StreamFrm_VisualizeMotionVectorsToolStripMenuItem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StreamFrm_VisualizeBlockTypesToolStripMenuItem() As Boolean
            Get
                Return CType(Me("StreamFrm_VisualizeBlockTypesToolStripMenuItem"),Boolean)
            End Get
            Set
                Me("StreamFrm_VisualizeBlockTypesToolStripMenuItem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StreamFrm_FFmpegDeinterlacerToolStripMenuItem() As Boolean
            Get
                Return CType(Me("StreamFrm_FFmpegDeinterlacerToolStripMenuItem"),Boolean)
            End Get
            Set
                Me("StreamFrm_FFmpegDeinterlacerToolStripMenuItem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property StreamFrm_AspectOriginToolStripMenuItem() As Boolean
            Get
                Return CType(Me("StreamFrm_AspectOriginToolStripMenuItem"),Boolean)
            End Get
            Set
                Me("StreamFrm_AspectOriginToolStripMenuItem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StreamFrm_SizeOriginToolStripMenuItem() As Boolean
            Get
                Return CType(Me("StreamFrm_SizeOriginToolStripMenuItem"),Boolean)
            End Get
            Set
                Me("StreamFrm_SizeOriginToolStripMenuItem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SavePathTextBox() As String
            Get
                Return CType(Me("SavePathTextBox"),String)
            End Get
            Set
                Me("SavePathTextBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AVSCheckBox() As Boolean
            Get
                Return CType(Me("AVSCheckBox"),Boolean)
            End Get
            Set
                Me("AVSCheckBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PresetLabel() As String
            Get
                Return CType(Me("PresetLabel"),String)
            End Get
            Set
                Me("PresetLabel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MainWidth() As String
            Get
                Return CType(Me("MainWidth"),String)
            End Get
            Set
                Me("MainWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MainHeight() As String
            Get
                Return CType(Me("MainHeight"),String)
            End Get
            Set
                Me("MainHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MainX() As String
            Get
                Return CType(Me("MainX"),String)
            End Get
            Set
                Me("MainX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MainY() As String
            Get
                Return CType(Me("MainY"),String)
            End Get
            Set
                Me("MainY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MainWindowState() As String
            Get
                Return CType(Me("MainWindowState"),String)
            End Get
            Set
                Me("MainWindowState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property PriorityComboBox() As Integer
            Get
                Return CType(Me("PriorityComboBox"),Integer)
            End Get
            Set
                Me("PriorityComboBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("240")>  _
        Public Property EncListListView0() As Integer
            Get
                Return CType(Me("EncListListView0"),Integer)
            End Get
            Set
                Me("EncListListView0") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property OldVerCheckBox() As Boolean
            Get
                Return CType(Me("OldVerCheckBox"),Boolean)
            End Get
            Set
                Me("OldVerCheckBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Auto-select")>  _
        Public Property LangToolStripMenuItem() As String
            Get
                Return CType(Me("LangToolStripMenuItem"),String)
            End Get
            Set
                Me("LangToolStripMenuItem") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.KiraraEncoder.My.MySettings
            Get
                Return Global.KiraraEncoder.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
